# Generated by Django 4.2.23 on 2025-08-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extracted_face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='extracted_faces/'),
        ),
    ]
