# Generated by Django 4.2.23 on 2025-10-03 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_userprofile_extracted_face_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examorientetion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_url', models.FileField(blank=True, null=True, upload_to='exam_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='examsession',
            old_name='start_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='device_mac',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='signal_strength',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='wifi_ssid',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='reason',
        ),
        migrations.AddField(
            model_name='alert',
            name='national_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='national_id_photos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
