# Generated by Django 4.2.23 on 2025-10-04 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_examorientetion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='examorientetion',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='examsession',
            old_name='timestamp',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='examorientetion',
            name='video_url',
        ),
        migrations.AddField(
            model_name='examorientetion',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='exam_media/'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='autosave_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsession',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('submitted_answer', models.TextField()),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_detail', to='authentication.examsession')),
            ],
        ),
    ]
