# Generated by Django 4.2.23 on 2025-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_examquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='guidance/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
