# Generated by Django 4.2.23 on 2025-10-06 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_registrationguidance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.exam')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
        migrations.RenameField(
            model_name='examsession',
            old_name='ended_at',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='examsession',
            old_name='evaluated',
            new_name='is_submitted',
        ),
        migrations.RemoveField(
            model_name='examanswer',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='examanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='examanswer',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='examanswer',
            name='submitted_answer',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='autosave_data',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='submitted',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='user',
        ),
        migrations.AddField(
            model_name='examanswer',
            name='last_saved',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='selected_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='authentication.examsession'),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.question'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.exam'),
        ),
    ]
