version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/code/static
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: newuser
      POSTGRES_PASSWORD: QAZwsx123#
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
